name: platform
description: Flutter Platform Info package.
version: 0.0.1
homepage: https://github.com/mosamuhana
repository: https://github.com/mosamuhana/flutter_platform_info

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
